version: '3.7'
services:
    # Due to authentication type, mysql cannot be the latest
    db:
        image: mysql:5
        restart: always
        container_name: wordpress_database
        environment: 
            MYSQL_DATABASE: wp_database
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: augedigital
            MYSQL_ROOT_PASSWORD: augetecnologia
        networks:
            - wp-back
        volumes:
            - wp-data:/var/lib/mysql
    wp:
        depends_on:
            - db
        image: wordpress:latest
        container_name: wordpress
        restart: always
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: augedigital
            WORDPRESS_DB_NAME: wp_database
        volumes:
            - '.:/var/www/html/wp-content/themes/cvupdate'
        networks:
            - wp-back
networks:
    wp-back:
volumes:
    wp-data: